---
- name: learning to recall var data
  hosts: localhost
  connection: local

  vars:
          telecom: 
            - ericsson
            - alu
            - avaya
            - cisco

          heroes:
            marvel:
                    - spiderman
                    - ironman
                    - daredevil

            dc: 
                    - wonderwomen
                    - batman
                    - superman


  tasks:
          - name: print out spiderman
            debug:
                    msg: " {{ heroes.marvel[0] }} "

          - name: print out batman
            debug:
                    msg: " {{ heroes.dc[1] }} "

          - name: print out all dc heroes
            debug:
                    msg: " {{ heroes.dc }} "
                    # loop: " {{ heroes.dc }} " 

          - name: print out cicso
            debug:
                    msg: " {{ telecom[3] }} "

          - name: print out all dc and marvel heroes
            debug:
                    msg: " {{ heroes.marvel + heroes.dc }} "
