---
- name: using template module fo create a finished file
  hosts: planetexpress

  vars:
    ship_name: pequod
    type_of_ship: whaling ship
    engine_tech: sails
    type_of_fuel: wind

  tasks:
    - name: use template to render a finish file
      template:
        src: templates/ship.cfg.j2
        dest: ~/ship.cfg

