---
- name: print astros from vars
  hosts: localhost
  connection: local


  vars_files:
          - vars/astros.yml

  tasks:
          - name: print out Jessica Meir
            debug: 
              msg: " {{ astros.people[5].name }} "

          - name: print out all astros
            debug:
              msg: "{{ item.name }}"
            loop: "{{ astros.people }}"  

          - name: print out number of astros on ISS
            debug:
              msg: " {{ astros.number }} "        
