---
- name: replacing lines
  hosts: planetexpress

  vars: 
    - fileloc: "/var/log/bootstrap.log"

  tasks:
    - name: "Insert a line into {{ fileloc }}"
      lineinfile:
              path: "{{ fileloc }}"
              regexp: "^Setting up lib.*"
              line: "REDACTED BY ANSIBLE linefile module"
              backup: yes
      become: true        
